apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: express-trace
  labels:
    app: express-trace
# The bookshelf frontend replica set ensures that at least 3
# instances of the bookshelf app are running on the cluster.
# For more info about Pods see:
#   https://cloud.google.com/container-engine/docs/pods/
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: express-trace
        tier: frontend
    spec:
      containers:
      - name: express-trace
        # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
        image: gcr.io/ymg-stackdriver-trace/express-trace
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The process listens on port 8080 for web traffic by default.
        ports:
        - name: express-trace
          containerPort: 8080