apiVersion: v1
kind: ReplicationController
metadata:
  name: express-debug
spec:
  replicas: 3
  selector:
    app: express-debug
  template:
    metadata:
      name: express-debug
      labels:
        app: express-debug
    spec:
      containers:
      - name: express-debug
        # Replace [GCLOUD_PROJECT] with your project ID or use `make template`.
        image: gcr.io/ymg-stackdriver-debug/express-trace
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: Always
        # The process listens on port 8080 for web traffic by default.
        ports:
        - name: express-debug
          containerPort: 8080